<!doctype html>
<html lang="en" data-theme="dark">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="dark light">
<title><?= esc($title ?? 'POS Lab') ?></title>
<script>document.documentElement.dataset.theme=localStorage.getItem('pos-theme')||'dark';</script>
<style>
:root{--bg:#0d0e0e;--surface:rgba(25,26,25,.74);--solid:#191a19;--ink:#f2f1ec;--muted:#aaa9a3;--dim:#73736f;--line:rgba(242,241,236,.14);--strong:rgba(242,241,236,.28);--accent:#a79aff;--soft:rgba(167,154,255,.12);--wash:rgba(167,154,255,.045);--shadow:rgba(0,0,0,.34);--radius:14px}
:root[data-theme="light"]{--bg:#eeefec;--surface:rgba(255,255,252,.76);--solid:#fbfbf8;--ink:#141514;--muted:#60615d;--dim:#888983;--line:rgba(20,21,20,.14);--strong:rgba(20,21,20,.3);--accent:#5b4fd8;--soft:rgba(91,79,216,.1);--wash:rgba(91,79,216,.035);--shadow:rgba(45,46,43,.12)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;min-width:320px;color:var(--ink);background-color:var(--bg);font:100%/1.5 ui-sans-serif,-apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",sans-serif;transition:background-color .35s ease,color .35s ease}body::before{content:"";position:fixed;inset:0;z-index:-1;pointer-events:none;background:radial-gradient(circle at 72% 8%,var(--wash),transparent 34rem)}a{color:inherit}button,a{-webkit-tap-highlight-color:transparent}.skip-link{position:fixed;left:1rem;top:-5rem;z-index:100;padding:.75rem 1rem;background:var(--ink);color:var(--bg);border-radius:999px}.skip-link:focus{top:1rem}
.site-header{position:sticky;top:0;z-index:30;border-bottom:1px solid var(--line);background:color-mix(in srgb,var(--bg) 74%,transparent);backdrop-filter:blur(24px) saturate(150%);-webkit-backdrop-filter:blur(24px) saturate(150%);box-shadow:inset 0 1px 0 rgba(255,255,255,.05)}.nav{width:min(1180px,calc(100% - 40px));height:72px;margin:auto;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:1.5rem}.brand{font-size:.82rem;font-weight:850;text-decoration:none;letter-spacing:.16em}nav{display:flex;gap:.2rem;align-items:center}nav a{padding:.55rem .75rem;color:var(--muted);text-decoration:none;font-size:.84rem;font-weight:650;border-radius:999px;transition:color .18s ease,background .18s ease,transform .1s ease}nav a:hover,nav a[aria-current="page"]{color:var(--ink);background:var(--soft)}nav a:active,.button:active,.theme-toggle:active{transform:scale(.97)}.nav-actions{display:flex;justify-content:flex-end}.theme-toggle{display:inline-flex;align-items:center;gap:.5rem;min-height:38px;padding:0 .8rem;border:1px solid var(--line);border-radius:999px;color:var(--ink);background:var(--surface);font:inherit;font-size:.78rem;font-weight:700;cursor:pointer;box-shadow:inset 0 1px 0 rgba(255,255,255,.08);transition:transform .1s ease,border-color .2s ease}.theme-toggle:hover{border-color:var(--strong)}.theme-icon{width:.65rem;height:.65rem;border-radius:50%;background:var(--ink);box-shadow:0 0 0 3px var(--soft)}
main{width:min(1180px,calc(100% - 40px));min-height:calc(100dvh - 160px);margin:auto;padding:clamp(3.5rem,8vw,7.5rem) 0 6rem}.eyebrow{color:var(--muted);font:750 .68rem/1.2 ui-monospace,"SFMono-Regular",Consolas,monospace;letter-spacing:.15em;text-transform:uppercase}h1,h2,h3,p{margin-top:0}h1{max-width:920px;margin:.85rem 0 1.5rem;font-size:clamp(3.5rem,9vw,7.8rem);line-height:.88;letter-spacing:-.07em;font-weight:760;text-wrap:balance}h2{font-size:clamp(2rem,4vw,4rem);line-height:.98;letter-spacing:-.05em}h3{margin-bottom:.55rem;font-size:clamp(1.15rem,2vw,1.45rem);letter-spacing:-.025em}p{max-width:690px;color:var(--muted);font-size:clamp(1rem,1.5vw,1.1rem);line-height:1.65}code{color:var(--ink);background:var(--soft);border-radius:6px;padding:.12em .35em;font-size:.9em}
.hero{position:relative;display:grid;grid-template-columns:1fr;min-height:min(680px,calc(100dvh - 120px));align-items:end;padding-bottom:clamp(3rem,7vw,6rem);border-bottom:1px solid var(--strong)}.hero-copy{position:relative;z-index:1}.hero p{max-width:610px;font-size:clamp(1.05rem,1.7vw,1.3rem)}.button{display:inline-flex;align-items:center;justify-content:center;margin-top:1.4rem;padding:.85rem 1.1rem;color:var(--bg);background:var(--ink);border:1px solid var(--ink);border-radius:999px;text-decoration:none;font-size:.85rem;font-weight:800;white-space:nowrap;transition:transform .1s ease,opacity .2s ease}.button:hover{opacity:.82}
.grid{display:grid;grid-template-columns:1.2fr .9fr .9fr}.card{background:var(--surface);border:1px solid var(--line);border-radius:var(--radius);box-shadow:0 24px 70px var(--shadow),inset 0 1px 0 rgba(255,255,255,.06);backdrop-filter:blur(20px) saturate(130%);-webkit-backdrop-filter:blur(20px) saturate(130%)}.feature{min-height:260px;padding:clamp(1.5rem,3vw,2.5rem);border:0;border-right:1px solid var(--line);border-bottom:1px solid var(--line);background:color-mix(in srgb,var(--solid) 70%,transparent);box-shadow:none;backdrop-filter:none}.feature:first-child{background:var(--soft)}.feature:last-child{border-right:0}.feature p{margin-bottom:0;font-size:.93rem}.page-intro{display:grid;gap:1.5rem;padding-bottom:clamp(2.5rem,5vw,4.5rem);border-bottom:1px solid var(--strong)}.page-intro h1{margin-bottom:0}.page-intro p{margin-bottom:0}.about-panel{margin-top:2rem;padding:clamp(1.6rem,4vw,3.5rem)}.about-panel p{margin-bottom:0}.table-wrap{margin-top:2rem;overflow-x:auto;border-top:1px solid var(--strong);border-bottom:1px solid var(--strong)}table{width:100%;border-collapse:collapse;min-width:650px}th,td{padding:1.3rem 1rem;text-align:left;border-bottom:1px solid var(--line)}th{color:var(--dim);font:750 .66rem/1.2 ui-monospace,"SFMono-Regular",Consolas,monospace;letter-spacing:.14em;text-transform:uppercase}td{color:var(--muted)}td:first-child{color:var(--ink);font-size:1.08rem;font-weight:650}tbody tr{transition:background .18s ease}tbody tr:hover{background:var(--soft)}tbody tr:last-child td{border-bottom:0}.pill{display:inline-block;padding:.38rem .68rem;color:var(--ink);background:var(--soft);border:1px solid var(--line);border-radius:999px;font-size:.78rem;font-weight:750}
footer{width:min(1180px,calc(100% - 40px));margin:auto;padding:1.5rem 0 2.5rem;display:flex;justify-content:space-between;gap:1rem;color:var(--dim);border-top:1px solid var(--line);font-size:.78rem}.reveal,.grid .feature{animation:reveal .65s cubic-bezier(.22,1,.36,1) both}.grid .feature:nth-child(2){animation-delay:.08s}.grid .feature:nth-child(3){animation-delay:.16s}@keyframes reveal{from{opacity:0;transform:translateY(18px)}to{opacity:1;transform:none}}:focus-visible{outline:2px solid var(--accent);outline-offset:4px}
@media(max-width:780px){.nav{width:min(100% - 28px,1180px);height:64px;grid-template-columns:auto 1fr}nav{position:fixed;left:14px;right:14px;bottom:14px;z-index:50;justify-content:space-around;padding:.35rem;border:1px solid var(--line);border-radius:999px;background:color-mix(in srgb,var(--bg) 80%,transparent);backdrop-filter:blur(22px) saturate(150%);box-shadow:0 14px 45px var(--shadow)}nav a{padding:.55rem .65rem;font-size:.74rem}main{width:min(100% - 28px,1180px);padding-top:3.5rem;padding-bottom:7rem}.hero,.page-intro{grid-template-columns:1fr}.hero{min-height:auto;align-items:start;padding-bottom:3.5rem}.hero::after{width:70vw;top:8%;right:-20%}.hero h1{max-width:9ch}.hero-aside{max-width:420px}.grid{grid-template-columns:1fr}.feature{min-height:0;border-right:0}footer{width:min(100% - 28px,1180px);flex-direction:column;padding-bottom:6.5rem}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}*,*::before,*::after{animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important}}@media(prefers-reduced-transparency:reduce){.site-header,nav,.card{background:var(--solid);backdrop-filter:none;-webkit-backdrop-filter:none}}@media(prefers-contrast:more){:root{--line:rgba(255,255,255,.34);--strong:rgba(255,255,255,.6)}:root[data-theme="light"]{--line:rgba(0,0,0,.34);--strong:rgba(0,0,0,.6)}}
.motion-ready body::before{animation:ambient 18s ease-in-out infinite alternate}.motion-ready .reveal-on-scroll{opacity:0;transform:translateY(22px);transition:opacity .7s cubic-bezier(.22,1,.36,1),transform .7s cubic-bezier(.22,1,.36,1)}.motion-ready .reveal-on-scroll.is-visible{opacity:1;transform:none}.button{position:relative;overflow:hidden}.button::after{content:"";position:absolute;inset:0;transform:translateX(-110%);background:linear-gradient(105deg,transparent 35%,rgba(255,255,255,.32),transparent 65%);transition:transform .65s cubic-bezier(.22,1,.36,1)}.button:hover::after{transform:translateX(110%)}.feature{transition:background .25s ease,transform .35s cubic-bezier(.22,1,.36,1),border-color .25s ease}.feature:hover{transform:translateY(-5px);border-color:var(--strong)}@keyframes ambient{from{transform:scale(1) translate3d(0,0,0);opacity:.75}to{transform:scale(1.08) translate3d(-2%,2%,0);opacity:1}}
</style>
<style>
.page-intro .button{justify-self:start;margin-top:0}.record-form{max-width:680px;margin-top:2rem;padding:clamp(1.5rem,4vw,3rem)}.field{display:grid;gap:.55rem;margin-bottom:1.35rem}.field label{color:var(--ink);font-size:.86rem;font-weight:750}.field input{width:100%;min-height:46px;padding:.75rem .85rem;border:1px solid var(--strong);border-radius:10px;background:var(--bg);color:var(--ink);font:inherit}.field input[type=file]{padding:.55rem}.field input[aria-invalid=true]{border-color:#e58187}.field-error{color:#f0a4a8;font-size:.85rem}.field-help{color:var(--muted);font-size:.83rem}.form-actions{display:flex;align-items:center;gap:1.25rem}.form-actions .button{margin-top:0;cursor:pointer}.text-link{color:var(--accent);font-weight:750;text-underline-offset:4px}.avatar{display:block;width:48px;height:48px;object-fit:cover;border-radius:12px;background:var(--soft)}.avatar-preview{width:80px;height:80px}.notice{margin-top:1.5rem;padding:.85rem 1rem;border:1px solid var(--strong);border-radius:10px;color:var(--ink);background:var(--soft)}
</style>
</head>
<body>
<?php $path = trim(service('uri')->getPath(), '/'); ?>
<a class="skip-link" href="#content">Skip to content</a>
<header class="site-header"><div class="nav"><a class="brand" href="<?= base_url('/') ?>">POS LAB</a><nav aria-label="Main navigation"><a href="<?= base_url('/') ?>" <?= $path === '' ? 'aria-current="page"' : '' ?>>Home</a><a href="<?= base_url('about') ?>" <?= $path === 'about' ? 'aria-current="page"' : '' ?>>About</a><?php if (session()->get('user') !== null): ?><a href="<?= base_url('customers') ?>" <?= str_starts_with($path, 'customers') ? 'aria-current="page"' : '' ?>>Customers</a><a href="<?= base_url('users') ?>" <?= str_starts_with($path, 'users') ? 'aria-current="page"' : '' ?>>Users</a><a href="<?= site_url('logout') ?>">Log out</a><?php else: ?><a href="<?= base_url('login') ?>" <?= $path === 'login' ? 'aria-current="page"' : '' ?>>Staff login</a><?php endif; ?></nav><div class="nav-actions"><button class="theme-toggle" type="button" aria-label="Switch color theme"><span class="theme-icon" aria-hidden="true"></span><span class="theme-label">Light</span></button></div></div></header>
<main id="content" class="reveal"><?= $this->renderSection('content') ?></main>
<footer><span>CodeIgniter 4 MVC laboratory activity · Customer and user accounts.</span><span>POS LAB</span></footer>
<script>const root=document.documentElement,label=document.querySelector('.theme-label');function sync(){label.textContent=root.dataset.theme==='dark'?'Light':'Dark'}sync();document.querySelector('.theme-toggle').addEventListener('click',()=>{root.dataset.theme=root.dataset.theme==='dark'?'light':'dark';localStorage.setItem('pos-theme',root.dataset.theme);sync()});document.body.classList.add('motion-ready');const observed=document.querySelectorAll('.feature,.table-wrap,.about-panel');observed.forEach((el,i)=>{el.classList.add('reveal-on-scroll');el.style.transitionDelay=(i*70)+'ms'});if('IntersectionObserver' in window){const observer=new IntersectionObserver((entries,io)=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');io.unobserve(entry.target)}}),{threshold:.14});observed.forEach(el=>observer.observe(el))}else{observed.forEach(el=>el.classList.add('is-visible'))}</script>
</body></html>
